name: doc-ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Configure Git credentials
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      # Set up Python environment
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install MkDocs
      - run: pip install mkdocs-material mkdocstrings-python

      # Read version from VERSION file
      - name: Read VERSION file
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      # Build documentation using MkDocs
      - name: Build MkDocs
        run: mkdocs build --clean

      # Switch to gh-pages branch and move files
      - name: Deploy to gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages
          
          # Create versioned directory for the new version
          mkdir -p ${{ env.VERSION }}
          cp -r site/* ${{ env.VERSION }}/
          
          # Update versions.json to match mike format
          if [ -f versions.json ]; then
            versions=$(cat versions.json | jq -c ". + [{\"version\": \"${{ env.VERSION }}\", \"title\": \"${{ env.VERSION }}\", \"aliases\": []}] | unique_by(.version)")
            echo $versions > versions.json
          else
            echo "[{\"version\": \"${{ env.VERSION }}\", \"title\": \"${{ env.VERSION }}\", \"aliases\": []}]" > versions.json
          fi

          # Commit and push changes
          git add .
          git commit -m "Deploy version ${{ env.VERSION }}"
          git push origin gh-pages

      # Update index.html to redirect to the latest version
      # Update index.html to redirect to the latest version
      - name: Update index.html
        run: |
          latest_version=$(cat versions.json | jq -r '.[-1].version')
          sed "s/VERSION_PLACEHOLDER/${latest_version}/g" .github/workflows/index-template.html > index.html
          
          # Check if index.html was modified
          if ! git diff --exit-code index.html; then
            git add index.html
            git commit -m "Update index.html to redirect to $latest_version"
            git push origin gh-pages
          else
            echo "No changes in index.html, skipping commit."
          fi

